-- =============================================================
-- 编程题库与编程比赛（2026-10-06）
--
-- 用途：学生端「AI 编程实验室」的题库、比赛、报名/成绩；管理端「编程题库」菜单。
-- 执行：mysql --default-character-set=utf8mb4 -uroot -p123456 nexora < 20261006_coding_problem.sql
-- 特性：幂等（CREATE TABLE IF NOT EXISTS + INSERT ... ON DUPLICATE KEY UPDATE），可重复执行。
-- 说明：coding_problem_record（单题练习流水）本期只建表，落库与掌握度回写属二期。
-- =============================================================

-- ---------- 1. 编程题库 ----------
CREATE TABLE IF NOT EXISTS `coding_problem` (
  `problem_id` varchar(32) NOT NULL COMMENT '题目ID',
  `stage` varchar(20) NOT NULL COMMENT '学段：PRIMARY_HIGH/JUNIOR/SENIOR',
  `grade` varchar(20) NULL COMMENT '年级（可空）',
  `knowledge_point_id` varchar(32) NULL COMMENT '知识点ID（二期用于掌握度回写）',
  `difficulty` tinyint(4) NOT NULL DEFAULT 1 COMMENT '难度：1入门 2基础 3进阶 4挑战',
  `title` varchar(120) NOT NULL COMMENT '题目标题',
  `goal` varchar(500) NULL COMMENT '一句话目标',
  `description` text NULL COMMENT '题目描述（Markdown）',
  `hint` text NULL COMMENT '思路提示',
  `starter_code` text NULL COMMENT '预置代码框架（脚手架）',
  `reference_code` text NULL COMMENT '参考答案（不随列表下发）',
  `solution_notes` text NULL COMMENT '答案讲解',
  `judge_type` tinyint(4) NOT NULL DEFAULT 1 COMMENT '判定：1关键词包含 2输出精确匹配 3正则',
  `expected_output` text NULL COMMENT '期望输出（judge_type=2）',
  `expected_keywords` varchar(500) NULL COMMENT '期望关键词（judge_type=1，逗号分隔，命中任一即通过）',
  `expected_pattern` varchar(500) NULL COMMENT '期望正则（judge_type=3）',
  `score` int(11) NOT NULL DEFAULT 10 COMMENT '积分（难度建议 10/20/30/50）',
  `estimate_minutes` int(11) NOT NULL DEFAULT 10 COMMENT '预估时长（分钟）',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '同难度内由易到难排序',
  `language` varchar(20) NOT NULL DEFAULT 'python' COMMENT '语言',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '0下架 1上架',
  `create_by` int(11) NULL COMMENT '创建人（管理员ID）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`problem_id`) USING BTREE,
  INDEX `idx_stage_diff`(`stage`, `difficulty`) USING BTREE,
  INDEX `idx_kp`(`knowledge_point_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '编程题库' ROW_FORMAT = Dynamic;

-- ---------- 2. 编程比赛 ----------
CREATE TABLE IF NOT EXISTS `coding_contest` (
  `contest_id` varchar(32) NOT NULL COMMENT '比赛ID',
  `title` varchar(120) NOT NULL COMMENT '比赛名称',
  `stage` varchar(20) NOT NULL COMMENT '面向学段（发布时选择，学生只看本学段）',
  `description` text NULL COMMENT '比赛说明（Markdown：规则/奖励）',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `duration_minutes` int(11) NULL COMMENT '单场限时（分钟，空=不限时）',
  `allow_answer` tinyint(4) NOT NULL DEFAULT 0 COMMENT '比赛期间是否允许看答案：0否 1是',
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0草稿 1已发布 2已结束',
  `create_by` int(11) NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`contest_id`) USING BTREE,
  INDEX `idx_stage_status`(`stage`, `status`) USING BTREE,
  INDEX `idx_time`(`start_time`, `end_time`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '编程比赛' ROW_FORMAT = Dynamic;

-- ---------- 3. 比赛赛题 ----------
CREATE TABLE IF NOT EXISTS `coding_contest_problem` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `contest_id` varchar(32) NOT NULL COMMENT '比赛ID',
  `problem_id` varchar(32) NOT NULL COMMENT '题目ID',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '赛题顺序',
  `score_override` int(11) NULL COMMENT '覆盖分值（空=取题目积分）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_contest_problem`(`contest_id`, `problem_id`) USING BTREE,
  INDEX `idx_contest`(`contest_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '编程比赛赛题' ROW_FORMAT = Dynamic;

-- ---------- 4. 比赛报名/成绩（同一行贯穿：报名 → 比赛 → 提交） ----------
CREATE TABLE IF NOT EXISTS `coding_contest_record` (
  `record_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `contest_id` varchar(32) NOT NULL COMMENT '比赛ID',
  `user_id` varchar(32) NOT NULL COMMENT '学生ID',
  `stage` varchar(20) NOT NULL COMMENT '学段【冗余快照】',
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0已报名 1比赛中 2已提交',
  `enroll_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '报名时间',
  `started_at` datetime NULL COMMENT '进入比赛时间',
  `submitted_at` datetime NULL COMMENT '提交时间',
  `score` int(11) NOT NULL DEFAULT 0 COMMENT '得分',
  `solved_count` int(11) NOT NULL DEFAULT 0 COMMENT '解出题数',
  `total_count` int(11) NOT NULL DEFAULT 0 COMMENT '赛题总数【快照】',
  `duration` int(11) NOT NULL DEFAULT 0 COMMENT '用时（秒）',
  PRIMARY KEY (`record_id`) USING BTREE,
  UNIQUE INDEX `uk_user_contest`(`user_id`, `contest_id`) USING BTREE,
  INDEX `idx_contest_score`(`contest_id`, `score`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '编程比赛报名与成绩' ROW_FORMAT = Dynamic;

-- ---------- 5. 单题练习流水（二期启用：落库 + 掌握度回写） ----------
CREATE TABLE IF NOT EXISTS `coding_problem_record` (
  `record_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `user_id` varchar(32) NOT NULL COMMENT '学生ID',
  `problem_id` varchar(32) NOT NULL COMMENT '题目ID',
  `stage` varchar(20) NOT NULL COMMENT '学段【冗余快照】',
  `difficulty` tinyint(4) NOT NULL DEFAULT 1 COMMENT '难度【冗余快照】',
  `is_passed` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否通过：0否 1是',
  `used_answer` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否看过答案：0否 1是',
  `score_gained` int(11) NOT NULL DEFAULT 0 COMMENT '实得积分',
  `duration` int(11) NOT NULL DEFAULT 0 COMMENT '用时（秒）',
  `code` text NULL COMMENT '提交代码【快照】',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`record_id`) USING BTREE,
  UNIQUE INDEX `uk_user_problem`(`user_id`, `problem_id`) USING BTREE,
  INDEX `idx_user_time`(`user_id`, `create_time`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '编程练习流水（二期）' ROW_FORMAT = Dynamic;

-- =============================================================
-- 预置题库：小学高年级 8 题（1 入门 → 4 挑战，由易到难）
-- =============================================================
INSERT INTO `coding_problem` (`problem_id`,`stage`,`difficulty`,`title`,`goal`,`description`,`hint`,`starter_code`,`reference_code`,`solution_notes`,`judge_type`,`expected_keywords`,`expected_pattern`,`expected_output`,`score`,`estimate_minutes`,`sort`,`language`,`status`) VALUES
('cp-ph-01','PRIMARY_HIGH',1,'星星塔','用循环打印一座 5 层星星塔','每一层的星星数量等于层号。请补全循环，让第 1 层 1 颗星、第 5 层 5 颗星，最后再打印一句话。','先想清楚「重复几次」，再想清楚「每次打印什么」。Python 里 "★" * 3 就是三颗星。','layers = 5\n\n# TODO: 用 for 循环逐层打印星星\nfor level in range(1, layers + 1):\n    pass\n\nprint("塔搭好啦！一共", layers, "层")','layers = 5\n\nfor level in range(1, layers + 1):\n    print("★" * level)\n\nprint("塔搭好啦！一共", layers, "层")','循环变量 level 从 1 变到 5，每次打印 level 颗星，就把「重复次数」和「重复内容」分开了——这是循环最重要的一步。',1,'★,塔搭好啦','','',10,8,1,'python',1),
('cp-ph-02','PRIMARY_HIGH',1,'九九乘法表','打印 1~9 的乘法表','用双重循环打印乘法表：第 a 行有 a 个算式，形如 1×3=3 2×3=6 3×3=9。','外层控制行（第一个乘数），内层控制列（第二个乘数）；每行拼好字符串再打印。','# TODO: 用两层循环打印乘法表\nfor a in range(1, 10):\n    line = ""\n    for b in range(1, a + 1):\n        pass\n    print(line)','for a in range(1, 10):\n    line = ""\n    for b in range(1, a + 1):\n        line = line + str(b) + "×" + str(a) + "=" + str(a * b) + "  "\n    print(line)','双重循环是「行 × 列」思维：外层走一遍，内层走 a 遍，正好覆盖每一格。',1,'×,=','','',10,10,2,'python',1),
('cp-ph-03','PRIMARY_HIGH',2,'猜数字（二分法）','用最少的次数猜出 1~50 里的神秘数字','程序自己来猜：每次猜范围中间的数，根据大小缩小范围，直到猜中，并打印猜了几次。','每次把范围一分为二：猜大了就把上限降到 mid-1，猜小了就把下限升到 mid+1。','secret = 37\nlow, high = 1, 50\ntries = 0\n\nwhile low <= high:\n    guess = (low + high) // 2\n    tries += 1\n    print("第", tries, "次猜：", guess)\n    # TODO: 比较 guess 和 secret，猜中就 break，否则缩小范围\n    break','secret = 37\nlow, high = 1, 50\ntries = 0\n\nwhile low <= high:\n    guess = (low + high) // 2\n    tries += 1\n    print("第", tries, "次猜：", guess)\n    if guess == secret:\n        print("猜到啦！答案就是", secret, "，一共用了", tries, "次")\n        break\n    elif guess < secret:\n        low = guess + 1\n    else:\n        high = guess - 1','一次比较就能排除一半可能：50 个数最多 6 次就能猜中，这就是「二分查找」的思想。',1,'猜到','','',20,15,1,'python',1),
('cp-ph-04','PRIMARY_HIGH',2,'成绩单统计','算出一组成绩的平均分、最高分和及格人数','给定 7 个同学的分数，请打印平均分（保留 1 位小数）、最高分和及格（≥60）人数。','用 for 遍历列表累加；求平均注意除以 len(scores)；及格人数用 if 计数。','scores = [88, 92, 57, 73, 100, 64, 81]\n\ntotal = 0\n# TODO: 累加求平均分、最高分、及格人数\n\nprint("平均分：", round(total / len(scores), 1))\nprint("最高分：", max(scores))\nprint("及格人数：", 0, "人")','scores = [88, 92, 57, 73, 100, 64, 81]\n\ntotal = 0\nfor score in scores:\n    total = total + score\n\naverage = total / len(scores)\nprint("平均分：", round(average, 1))\nprint("最高分：", max(scores))\nprint("最低分：", min(scores))\n\npassed = 0\nfor score in scores:\n    if score >= 60:\n        passed = passed + 1\nprint("及格人数：", passed, "人")','「遍历 + 累加 + 条件计数」是数据处理的三板斧，成绩统计、词频统计都是这个套路。',1,'平均,及格','','',20,12,2,'python',1),
('cp-ph-05','PRIMARY_HIGH',2,'数字金字塔','打印一个 5 行数字金字塔','第 i 行先打印 (5-i) 个空格，再打印 i 个数字 i（用空格隔开），形成金字塔形状。','print 里默认会换行；想同行输出可以先把一行拼成一个字符串，再一次性 print。','rows = 5\n\nfor i in range(1, rows + 1):\n    spaces = " " * (rows - i)\n    # TODO: 拼出第 i 行的数字部分并打印\n    print(spaces)','rows = 5\n\nfor i in range(1, rows + 1):\n    spaces = " " * (rows - i)\n    numbers = " ".join([str(i)] * i)\n    print(spaces + numbers)','字符串乘法 " " * n 控制缩进，join 控制数字之间的间隔——排版类题目基本都用这两招。',1,'第,金字塔','','',20,15,3,'python',1),
('cp-ph-06','PRIMARY_HIGH',3,'杨辉三角','打印杨辉三角的前 6 行','每一行的首尾都是 1，中间的数是上一行相邻两数之和。','把上一行保存下来，下一行就可以由它算出来：row[j] = prev[j-1] + prev[j]。','rows = 6\nprev = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    # TODO: 用上一行算出中间的数字\n    print("杨辉三角第", i + 1, "行：", row)\n    prev = row','rows = 6\nprev = []\nfor i in range(rows):\n    row = [1] * (i + 1)\n    for j in range(1, i):\n        row[j] = prev[j - 1] + prev[j]\n    print("杨辉三角第", i + 1, "行：", row)\n    prev = row','用「上一行的结果」推导「下一行」，是动态规划最朴素的形状。',1,'杨辉三角','','',30,20,1,'python',1),
('cp-ph-07','PRIMARY_HIGH',3,'质数筛选','找出 2~50 之间的所有质数','质数是只能被 1 和自身整除的数。请输出 2~50 里所有的质数，并打印它们的个数。','判断 n 是不是质数，只要试除到 n 的平方根就行——超过平方根的因子一定和更小的因子配对。','def is_prime(n):\n    if n < 2:\n        return False\n    i = 2\n    while i * i <= n:\n        # TODO: 发现能整除就返回 False\n        i += 1\n    return True\n\nprimes = [n for n in range(2, 51) if is_prime(n)]\nprint("2~50 的质数共", len(primes), "个：", primes)','def is_prime(n):\n    if n < 2:\n        return False\n    i = 2\n    while i * i <= n:\n        if n % i == 0:\n            return False\n        i += 1\n    return True\n\nprimes = [n for n in range(2, 51) if is_prime(n)]\nprint("2~50 的质数共", len(primes), "个：", primes)','把「判断一个数」封装成函数，再用列表推导式批量处理，代码立刻短一半。',1,'质数','','',30,18,2,'python',1),
('cp-ph-08','PRIMARY_HIGH',4,'递归画分形','用递归打印一个分形三角形','用递归画出「谢尔宾斯基」式的星号三角形：把一个大三角形拆成 3 个小三角形，直到层数用尽。','递归函数要写清楚两件事：什么时候停下来（层数为 0 就打印），以及怎么把问题变小（层数减 1）。','def fractal(n, indent=0):\n    if n == 0:\n        return\n    # TODO: 打印当前层，再递归调用自己（层数减 1）\n    pass\n\nfractal(4)\nprint("分形绘制完成")','def fractal(n, indent=0):\n    if n == 0:\n        return\n    print(" " * indent + "★" * (n * 2 - 1))\n    fractal(n - 1, indent + 1)\n    print(" " * indent + "★" * (n * 2 - 1))\n\nfractal(4)\nprint("分形绘制完成")','递归 = 「自己调用自己 + 出口条件」。分形、树、目录遍历都是这种形状。',1,'分形','','',50,25,1,'python',1)
ON DUPLICATE KEY UPDATE `stage`=VALUES(`stage`), `difficulty`=VALUES(`difficulty`), `title`=VALUES(`title`), `goal`=VALUES(`goal`), `description`=VALUES(`description`), `hint`=VALUES(`hint`), `starter_code`=VALUES(`starter_code`), `reference_code`=VALUES(`reference_code`), `solution_notes`=VALUES(`solution_notes`), `judge_type`=VALUES(`judge_type`), `expected_keywords`=VALUES(`expected_keywords`), `score`=VALUES(`score`), `estimate_minutes`=VALUES(`estimate_minutes`), `sort`=VALUES(`sort`), `status`=VALUES(`status`);

-- =============================================================
-- 预置题库：初中 12 题（1 入门 → 4 挑战）
-- =============================================================
INSERT INTO `coding_problem` (`problem_id`,`stage`,`difficulty`,`title`,`goal`,`description`,`hint`,`starter_code`,`reference_code`,`solution_notes`,`judge_type`,`expected_keywords`,`expected_pattern`,`expected_output`,`score`,`estimate_minutes`,`sort`,`language`,`status`) VALUES
('cp-jr-01','JUNIOR',1,'圆的面积（格式化输出）','按格式输出圆的面积与周长','读入半径 r=3.5，输出面积与周长，均保留两位小数（π 取 3.14159）。','f-string 里用 {value:.2f} 可以保留两位小数。','import math\n\nr = 3.5\npi = 3.14159\n\n# TODO: 计算面积与周长并按格式输出\nprint(f"半径 {r} 的圆")','import math\n\nr = 3.5\npi = 3.14159\narea = pi * r * r\nperimeter = 2 * pi * r\n\nprint(f"半径 {r} 的圆")\nprint(f"面积：{area:.2f}")\nprint(f"周长：{perimeter:.2f}")','浮点数的格式化输出（保留几位小数）是编程里最常被忽略却最容易出错的细节。',1,'面积,周长','','',10,8,1,'python',1),
('cp-jr-02','JUNIOR',1,'回文判断','判断一句话是不是回文','回文指正着读和倒着读一样（如「上海自来水来自海上」）。请判断给出的两句话并打印结论。','Python 里 s[::-1] 就是倒序；先去掉空格更准确。','def is_palindrome(text):\n    cleaned = "".join(ch for ch in text if ch.strip() != "")\n    # TODO: 比较 cleaned 与它的倒序\n    return False\n\nfor sentence in ["上海自来水来自海上", "人工智能很有趣"]:\n    print(sentence, "→ 是回文" if is_palindrome(sentence) else "→ 不是回文")','def is_palindrome(text):\n    cleaned = "".join(ch for ch in text if ch.strip() != "")\n    return cleaned == cleaned[::-1]\n\nfor sentence in ["上海自来水来自海上", "人工智能很有趣"]:\n    print(sentence, "→ 是回文" if is_palindrome(sentence) else "→ 不是回文")','切片 s[::-1] 是 Python 的语法糖；用三元表达式把「是/不是」写在 print 里，可读性更好。',1,'回文','','',10,10,2,'python',1),
('cp-jr-03','JUNIOR',2,'列表去重并排序','把重复的成绩去重后从小到大输出','给定一组成绩（含重复），去重后升序输出，并说明去掉了几个重复值。','set() 天然去重但会打乱顺序，sorted() 负责排序；注意 set 转 list 后再排序。','scores = [88, 92, 88, 57, 73, 92, 100, 57, 81]\n\n# TODO: 去重 + 升序排序\nunique = sorted(scores)\nprint("去重后：", unique)\nprint("去掉了", len(scores) - len(unique), "个重复值")','scores = [88, 92, 88, 57, 73, 92, 100, 57, 81]\n\nunique = sorted(set(scores))\nprint("去重后：", unique)\nprint("去掉了", len(scores) - len(unique), "个重复值")','「集合去重 + 排序」是最常用的两件套；注意 set 之后顺序不可依赖。',1,'去重','','',20,12,1,'python',1),
('cp-jr-04','JUNIOR',2,'斐波那契前 N 项','输出斐波那契数列的前 10 项','1, 1, 2, 3, 5, 8… 每项等于前两项之和。请输出前 10 项与它们的总和。','用两个变量 a、b 交替往前滚：a, b = b, a + b。','a, b = 1, 1\nsequence = []\nfor _ in range(10):\n    # TODO: 收集当前项并前进\n    pass\n\nprint("斐波那契数列前 10 项：", sequence)\nprint("总和：", sum(sequence))','a, b = 1, 1\nsequence = []\nfor _ in range(10):\n    sequence.append(a)\n    a, b = b, a + b\n\nprint("斐波那契数列前 10 项：", sequence)\nprint("总和：", sum(sequence))','「多变量同时赋值」让状态滚动变得优雅：a, b = b, a + b 一行完成两个变量的更新。',1,'数列,总和','','',20,15,2,'python',1),
('cp-jr-05','JUNIOR',2,'单词计数','统计一句话里每个单词出现的次数','把句子按空格切开，统计每个单词出现次数，并按出现次数从多到少输出。','字典 get(word, 0) + 1 是计数的固定写法；sorted 里用 key 控制排序依据。','text = "人工智能 让 学习 更 有趣 人工智能 让 教学 更 高效"\n\ncounter = {}\nfor word in text.split():\n    # TODO: 统计词频\n    pass\n\nfor word, count in sorted(counter.items(), key=lambda item: -item[1]):\n    print(" ", word, "出现", count, "次")','text = "人工智能 让 学习 更 有趣 人工智能 让 教学 更 高效"\n\ncounter = {}\nfor word in text.split():\n    counter[word] = counter.get(word, 0) + 1\n\nfor word, count in sorted(counter.items(), key=lambda item: -item[1]):\n    print(" ", word, "出现", count, "次")','字典是「以键查值」的容器；排序时 key=lambda item: -item[1] 表示按次数降序。',1,'出现','','',20,15,3,'python',1),
('cp-jr-06','JUNIOR',2,'合并两个有序数组','把两个升序数组合并成一个升序数组','不使用 sort()，用双指针把两个已排序的数组线性合并。','两个指针分别指向两个数组头部，每次挑较小的那个放进结果，再让对应指针前进。','left = [1, 4, 7, 9]\nright = [2, 3, 8, 10]\n\ni = j = 0\nmerged = []\nwhile i < len(left) and j < len(right):\n    # TODO: 双指针挑选较小的放入 merged\n    pass\n\nmerged += left[i:] + right[j:]\nprint("合并结果：", merged)','left = [1, 4, 7, 9]\nright = [2, 3, 8, 10]\n\ni = j = 0\nmerged = []\nwhile i < len(left) and j < len(right):\n    if left[i] <= right[j]:\n        merged.append(left[i])\n        i += 1\n    else:\n        merged.append(right[j])\n        j += 1\n\nmerged += left[i:] + right[j:]\nprint("合并结果：", merged)','双指针是线性时间合并的关键；归并排序的「合并」步骤就是这段代码。',1,'合并结果','','',20,18,4,'python',1),
('cp-jr-07','JUNIOR',3,'二分查找','在有序列表中查找目标值','返回目标值在列表中的下标，找不到返回 -1，并打印比较了几次。','每次取中间位置比较，根据大小把区间砍掉一半；循环条件是 low <= high。','data = [3, 8, 15, 23, 42, 57, 68, 91]\ntarget = 57\n\nlow, high = 0, len(data) - 1\nsteps = 0\nwhile low <= high:\n    # TODO: 二分查找，统计 steps\n    pass\n\nprint("查找结束")','data = [3, 8, 15, 23, 42, 57, 68, 91]\ntarget = 57\n\nlow, high = 0, len(data) - 1\nsteps = 0\nwhile low <= high:\n    mid = (low + high) // 2\n    steps += 1\n    if data[mid] == target:\n        print("找到", target, "，下标是", mid, "，比较了", steps, "次")\n        break\n    elif data[mid] < target:\n        low = mid + 1\n    else:\n        high = mid - 1\nelse:\n    print("没找到", target, "，返回 -1")\nprint("查找结束")','二分的本质是「每次排除一半」；while-else 在循环没被 break 时执行，正好表达「没找到」。',1,'下标,比较了','','',30,20,1,'python',1),
('cp-jr-08','JUNIOR',3,'矩阵转置','把一个 3×4 矩阵转置成 4×3','转置就是行列互换：原矩阵第 i 行第 j 列，转置后到第 j 行第 i 列。','用两层循环构造新矩阵：result[j][i] = matrix[i][j]；也可以一行写成 zip(*matrix)。','matrix = [\n    [1, 2, 3, 4],\n    [5, 6, 7, 8],\n    [9, 10, 11, 12],\n]\n\n# TODO: 转置\nresult = []\nfor row in result:\n    print("转置后：", row)','matrix = [\n    [1, 2, 3, 4],\n    [5, 6, 7, 8],\n    [9, 10, 11, 12],\n]\n\nresult = [[0] * len(matrix) for _ in range(len(matrix[0]))]\nfor i in range(len(matrix)):\n    for j in range(len(matrix[i])):\n        result[j][i] = matrix[i][j]\n\nfor row in result:\n    print("转置后：", row)','二维列表的行列下标要分清；嵌套列表推导式负责「先建好空矩阵」。',1,'转置后','','',30,20,2,'python',1),
('cp-jr-09','JUNIOR',3,'字符串压缩','把连续重复字符压缩成「字符+次数」','如 aaabbc → a3b2c1。请实现压缩并打印压缩前后长度。','遍历字符串，比较当前字符与前一个是否相同，相同则计数加一，否则把上一组写入结果。','text = "aaabbccccdde"\n\ncompressed = ""\ncount = 1\nfor i in range(1, len(text)):\n    # TODO: 统计连续相同字符\n    pass\n\nprint("压缩结果：", compressed)\nprint("压缩前长度：", len(text), "，压缩后长度：", len(compressed))','text = "aaabbccccdde"\n\ncompressed = ""\ncount = 1\nfor i in range(1, len(text)):\n    if text[i] == text[i - 1]:\n        count += 1\n    else:\n        compressed += text[i - 1] + str(count)\n        count = 1\ncompressed += text[-1] + str(count)\n\nprint("压缩结果：", compressed)\nprint("压缩前长度：", len(text), "，压缩后长度：", len(compressed))','「循环里比较相邻元素」是字符串处理的基本功；注意循环结束后最后一组要补写。',1,'压缩结果','','',30,20,3,'python',1),
('cp-jr-10','JUNIOR',3,'成绩等级统计','按等级统计人数并输出','把成绩按 优秀(≥90)/良好(≥75)/及格(≥60)/待提高 分档，统计各档人数与占比。','先定义分档函数，再遍历统计；占比用 round(数量 / 总数 * 100, 1)。','scores = [88, 92, 57, 73, 100, 64, 81, 95, 45]\n\ndef level_of(score):\n    # TODO: 返回等级名称\n    return "待提高"\n\ncounter = {}\nfor score in scores:\n    name = level_of(score)\n    counter[name] = counter.get(name, 0) + 1\n\nfor name, count in counter.items():\n    print(f"{name}：{count} 人，占 {round(count / len(scores) * 100, 1)}%")','scores = [88, 92, 57, 73, 100, 64, 81, 95, 45]\n\ndef level_of(score):\n    if score >= 90:\n        return "优秀"\n    if score >= 75:\n        return "良好"\n    if score >= 60:\n        return "及格"\n    return "待提高"\n\ncounter = {}\nfor score in scores:\n    name = level_of(score)\n    counter[name] = counter.get(name, 0) + 1\n\nfor name, count in counter.items():\n    print(f"{name}：{count} 人，占 {round(count / len(scores) * 100, 1)}%")','把「判断规则」抽成函数，统计逻辑就与业务规则解耦了——分档规则改了只改一处。',1,'优秀,及格','','',30,20,4,'python',1),
('cp-jr-11','JUNIOR',4,'约瑟夫环','模拟报数出列，输出出列顺序','n 个人围成一圈，从 1 开始报数，报到 m 的人出列，然后从下一个人重新报数，直到所有人出列。','用列表模拟圆圈，出列后把该元素删掉，注意下标的取模回绕。','n, m = 10, 3\npeople = list(range(1, n + 1))\norder = []\nindex = 0\n\nwhile people:\n    # TODO: 报数并让第 m 个人出列\n    pass\n\nprint("出列顺序：", order)','n, m = 10, 3\npeople = list(range(1, n + 1))\norder = []\nindex = 0\n\nwhile people:\n    index = (index + m - 1) % len(people)\n    order.append(people.pop(index))\n\nprint("出列顺序：", order)','取模是「圆圈」的关键：(下标 + m - 1) % 人数 会自动绕回开头。',1,'出列顺序','','',50,25,1,'python',1),
('cp-jr-12','JUNIOR',4,'全排列','输出 1~4 的所有排列','用递归生成 1,2,3,4 的全排列（共 24 种），并打印总数。','递归的每一步：从剩下的数字里选一个放到当前位置，剩下的交给下一层。','def permutations(nums):\n    if len(nums) <= 1:\n        return [nums]\n    result = []\n    for i in range(len(nums)):\n        # TODO: 固定第 i 个数字，递归排列剩下的\n        pass\n    return result\n\nall_perm = permutations([1, 2, 3, 4])\nprint("前 6 种排列：", all_perm[:6])\nprint("排列总数：", len(all_perm))','def permutations(nums):\n    if len(nums) <= 1:\n        return [nums]\n    result = []\n    for i in range(len(nums)):\n        rest = nums[:i] + nums[i + 1:]\n        for item in permutations(rest):\n            result.append([nums[i]] + item)\n    return result\n\nall_perm = permutations([1, 2, 3, 4])\nprint("前 6 种排列：", all_perm[:6])\nprint("排列总数：", len(all_perm))','「选一个 + 递归剩下」是回溯法的雏形；4! = 24 种也验证了结果正确。',1,'排列总数','','',50,30,2,'python',1)
ON DUPLICATE KEY UPDATE `stage`=VALUES(`stage`), `difficulty`=VALUES(`difficulty`), `title`=VALUES(`title`), `goal`=VALUES(`goal`), `description`=VALUES(`description`), `hint`=VALUES(`hint`), `starter_code`=VALUES(`starter_code`), `reference_code`=VALUES(`reference_code`), `solution_notes`=VALUES(`solution_notes`), `judge_type`=VALUES(`judge_type`), `expected_keywords`=VALUES(`expected_keywords`), `score`=VALUES(`score`), `estimate_minutes`=VALUES(`estimate_minutes`), `sort`=VALUES(`sort`), `status`=VALUES(`status`);

-- =============================================================
-- 预置题库：高中 24 题（1 入门 → 4 挑战）
-- =============================================================
INSERT INTO `coding_problem` (`problem_id`,`stage`,`difficulty`,`title`,`goal`,`description`,`hint`,`starter_code`,`reference_code`,`solution_notes`,`judge_type`,`expected_keywords`,`expected_pattern`,`expected_output`,`score`,`estimate_minutes`,`sort`,`language`,`status`) VALUES
('cp-sr-01','SENIOR',1,'冒泡排序过程打印','实现冒泡排序并打印每一轮结果','对给定数组做升序冒泡排序，每完成一轮打印当前状态，最后打印结果。','外层控制轮数，内层两两比较交换；每轮结束最大的元素会冒到末尾。','data = [5, 2, 9, 1, 7, 3]\n\nfor i in range(len(data) - 1):\n    # TODO: 内层比较并交换\n    print("第", i + 1, "轮后：", data)\n\nprint("排序完成：", data)','data = [5, 2, 9, 1, 7, 3]\n\nfor i in range(len(data) - 1):\n    for j in range(len(data) - 1 - i):\n        if data[j] > data[j + 1]:\n            data[j], data[j + 1] = data[j + 1], data[j]\n    print("第", i + 1, "轮后：", data)\n\nprint("排序完成：", data)','冒泡的关键是「内层比较范围逐轮缩小」（已就位的尾部不再比较）。',1,'轮后,排序完成','','',10,10,1,'python',1),
('cp-sr-02','SENIOR',1,'选择排序与交换次数','实现选择排序并统计交换次数','每轮从未排序区间选出最小值放到已排序区间末尾，统计发生了几次交换。','用 min_index 记录最小值下标，一轮结束再交换一次（这就是它交换次数比冒泡少的原因）。','data = [64, 25, 12, 22, 11, 90]\n\nswaps = 0\nfor i in range(len(data) - 1):\n    min_index = i\n    # TODO: 找到最小值下标并交换，统计 swaps\n    pass\n\nprint("排序结果：", data)\nprint("交换次数：", swaps)','data = [64, 25, 12, 22, 11, 90]\n\nswaps = 0\nfor i in range(len(data) - 1):\n    min_index = i\n    for j in range(i + 1, len(data)):\n        if data[j] < data[min_index]:\n            min_index = j\n    if min_index != i:\n        data[i], data[min_index] = data[min_index], data[i]\n        swaps += 1\n\nprint("排序结果：", data)\nprint("交换次数：", swaps)','选择排序每轮只交换一次，交换次数最多 n-1 次，比冒泡更省写操作。',1,'交换次数,排序结果','','',10,12,2,'python',1),
('cp-sr-03','SENIOR',2,'二分查找实现','在有序数组中查找并返回下标','实现二分查找，返回目标下标（找不到返回 -1），打印比较次数与结果。','循环不变量：目标一定在 [low, high] 内；每次比较后把一半区间排除掉。','data = [3, 8, 15, 23, 42, 57, 68, 91]\ntarget = 23\n\ndef binary_search(nums, value):\n    low, high = 0, len(nums) - 1\n    steps = 0\n    # TODO: 实现二分查找，返回 (下标, 比较次数)\n    return -1, steps\n\nindex, steps = binary_search(data, target)\nprint("目标", target, "下标为", index, "，比较", steps, "次")','data = [3, 8, 15, 23, 42, 57, 68, 91]\ntarget = 23\n\ndef binary_search(nums, value):\n    low, high = 0, len(nums) - 1\n    steps = 0\n    while low <= high:\n        mid = (low + high) // 2\n        steps += 1\n        if nums[mid] == value:\n            return mid, steps\n        if nums[mid] < value:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1, steps\n\nindex, steps = binary_search(data, target)\nprint("目标", target, "下标为", index, "，比较", steps, "次")','二分查找的时间复杂度是 O(log n)：8 个元素最多比较 4 次。',1,'下标为,比较','','',20,15,1,'python',1),
('cp-sr-04','SENIOR',2,'词频 Top5','统计词频并输出前 5 名','统计一段文字的词频，按次数降序输出前 5 个词及其占比。','字典计数 + sorted(key=lambda) 排序；占比用 round(count / total * 100, 1)。','text = "人工智能 让 学习 更 有趣 人工智能 让 教学 更 高效 人工智能 助手 陪学 更 贴心"\n\ncounter = {}\nfor word in text.split():\n    counter[word] = counter.get(word, 0) + 1\n\n# TODO: 排序并输出前 5 名与占比\ntotal = len(text.split())','text = "人工智能 让 学习 更 有趣 人工智能 让 教学 更 高效 人工智能 助手 陪学 更 贴心"\n\ncounter = {}\nfor word in text.split():\n    counter[word] = counter.get(word, 0) + 1\n\ntotal = len(text.split())\nfor word, count in sorted(counter.items(), key=lambda item: -item[1])[:5]:\n    print(f"{word}：{count} 次，占比 {round(count / total * 100, 1)}%")','词频统计是「字典 + 排序 + 切片」的经典组合，也是文本分析的第一步。',1,'占比','','',20,15,2,'python',1),
('cp-sr-05','SENIOR',2,'括号匹配','判断括号序列是否合法','判断只含 ()[]{} 的字符串是否合法：每个左括号都有正确的右括号与之配对且顺序正确。','用栈：遇到左括号入栈，遇到右括号检查栈顶是否配对；结束后栈必须为空。','def is_valid(text):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for ch in text:\n        # TODO: 用栈判断括号是否匹配\n        pass\n    return len(stack) == 0\n\nfor case in ["({[]})", "([)]", "((("]:\n    print(case, "→", "合法" if is_valid(case) else "不合法")','def is_valid(text):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for ch in text:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if not stack or stack[-1] != pairs[ch]:\n                return False\n            stack.pop()\n    return len(stack) == 0\n\nfor case in ["({[]})", "([)]", "((("]:\n    print(case, "→", "合法" if is_valid(case) else "不合法")','「后进先出」的配对问题一律用栈：编译器检查语法、浏览器解析 HTML 都是这个思路。',1,'合法,不合法','','',20,18,3,'python',1),
('cp-sr-06','SENIOR',3,'最大子段和','求连续子数组的最大和','给定整数数组，找出和最大的连续子段并输出该和（允许长度为 1）。','维护「以当前位置结尾的最大和」：如果前面的和为负，还不如从当前重新开始。','data = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\n\nbest = data[0]\ncurrent = data[0]\nfor value in data[1:]:\n    # TODO: 更新 current 与 best\n    pass\n\nprint("最大子段和：", best)','data = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\n\nbest = data[0]\ncurrent = data[0]\nfor value in data[1:]:\n    current = max(value, current + value)\n    best = max(best, current)\n\nprint("最大子段和：", best)','Kadane 算法只扫一遍 O(n)：每一步决定「接着前面」还是「从自己重新开始」。',1,'最大子段和','','',30,20,1,'python',1),
('cp-sr-07','SENIOR',3,'递归与记忆化','对比两种斐波那契实现的耗时','分别用朴素递归与字典记忆化求 fib(28)，打印结果与耗时差异。','递归会重复计算大量子问题；用字典把算过的结果缓存起来。','import time\n\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\ncache = {}\ndef fib_fast(n):\n    # TODO: 带记忆化的递归\n    return n\n\nstart = time.time()\nprint("朴素递归 fib(28) =", fib(28))\nprint("耗时：", round((time.time() - start) * 1000), "ms")','import time\n\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\ncache = {}\ndef fib_fast(n):\n    if n < 2:\n        return n\n    if n in cache:\n        return cache[n]\n    cache[n] = fib_fast(n - 1) + fib_fast(n - 2)\n    return cache[n]\n\nstart = time.time()\nprint("朴素递归 fib(28) =", fib(28))\nprint("耗时：", round((time.time() - start) * 1000), "ms")\n\nstart = time.time()\nprint("记忆化 fib(28) =", fib_fast(28))\nprint("耗时：", round((time.time() - start) * 1000), "ms")','同一份递推式，加一层缓存就从指数级降到线性——这就是动态规划的思想起点。',1,'耗时','','',30,20,2,'python',1),
('cp-sr-08','SENIOR',3,'快速排序','实现快速排序','用分治法实现快排：选基准，把小于基准的放左边、大于的放右边，再递归处理两侧。','列表推导式能让划分写得很短：[x for x in nums if x < pivot]。','def quick_sort(nums):\n    if len(nums) <= 1:\n        return nums\n    pivot = nums[len(nums) // 2]\n    # TODO: 划分并递归\n    return nums\n\ndata = [33, 10, 55, 71, 29, 3, 18]\nprint("排序结果：", quick_sort(data))','def quick_sort(nums):\n    if len(nums) <= 1:\n        return nums\n    pivot = nums[len(nums) // 2]\n    left = [x for x in nums if x < pivot]\n    mid = [x for x in nums if x == pivot]\n    right = [x for x in nums if x > pivot]\n    return quick_sort(left) + mid + quick_sort(right)\n\ndata = [33, 10, 55, 71, 29, 3, 18]\nprint("排序结果：", quick_sort(data))','快排平均 O(n log n)：每次划分把问题分成两半；最坏（已有序且取端点为基准）退化到 O(n²)。',1,'排序结果','','',30,20,3,'python',1),
('cp-sr-09','SENIOR',3,'归并排序','实现归并排序','用分治 + 双指针合并实现归并排序并输出结果。','先递归排好左右两半，再用双指针把两个有序列表合并。','def merge_sort(nums):\n    if len(nums) <= 1:\n        return nums\n    mid = len(nums) // 2\n    left = merge_sort(nums[:mid])\n    right = merge_sort(nums[mid:])\n    # TODO: 合并两个有序列表\n    return left + right\n\ndata = [38, 27, 43, 3, 9, 82, 10]\nprint("排序结果：", merge_sort(data))','def merge_sort(nums):\n    if len(nums) <= 1:\n        return nums\n    mid = len(nums) // 2\n    left = merge_sort(nums[:mid])\n    right = merge_sort(nums[mid:])\n    merged = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            merged.append(left[i])\n            i += 1\n        else:\n            merged.append(right[j])\n            j += 1\n    merged += left[i:] + right[j:]\n    return merged\n\ndata = [38, 27, 43, 3, 9, 82, 10]\nprint("排序结果：", merge_sort(data))','归并排序稳定、复杂度稳定 O(n log n)，代价是需要额外空间。',1,'排序结果','','',30,22,4,'python',1),
('cp-sr-10','SENIOR',3,'埃氏筛素数','用筛法统计 100 以内的素数','用埃拉托斯特尼筛法找出 2~100 的所有素数并打印个数与列表。','开一个布尔数组，从小到大把每个素数的倍数标记为非素数。','limit = 100\nis_prime = [True] * (limit + 1)\nis_prime[0] = is_prime[1] = False\n\nfor i in range(2, int(limit ** 0.5) + 1):\n    # TODO: 把 i 的倍数全部标记为非素数\n    pass\n\nprimes = [i for i in range(limit + 1) if is_prime[i]]\nprint("100 以内素数共", len(primes), "个：", primes)','limit = 100\nis_prime = [True] * (limit + 1)\nis_prime[0] = is_prime[1] = False\n\nfor i in range(2, int(limit ** 0.5) + 1):\n    if is_prime[i]:\n        for j in range(i * i, limit + 1, i):\n            is_prime[j] = False\n\nprimes = [i for i in range(limit + 1) if is_prime[i]]\nprint("100 以内素数共", len(primes), "个：", primes)','筛法把「逐个判断」变成「批量标记」，复杂度从 O(n√n) 降到 O(n log log n)。',1,'素数共','','',30,20,5,'python',1),
('cp-sr-11','SENIOR',3,'最长无重复子串','用滑动窗口求最长无重复子串','求不含重复字符的最长子串长度，并打印该子串。','左指针维护窗口左界，遇到重复字符时把左界移到重复位置之后。','text = "abcabcbb"\n\nleft = 0\nseen = {}\nbest_len = 0\nbest_str = ""\nfor right, ch in enumerate(text):\n    # TODO: 滑动窗口\n    pass\n\nprint("最长无重复子串：", best_str, "，长度", best_len)','text = "abcabcbb"\n\nleft = 0\nseen = {}\nbest_len = 0\nbest_str = ""\nfor right, ch in enumerate(text):\n    if ch in seen and seen[ch] >= left:\n        left = seen[ch] + 1\n    seen[ch] = right\n    if right - left + 1 > best_len:\n        best_len = right - left + 1\n        best_str = text[left:right + 1]\n\nprint("最长无重复子串：", best_str, "，长度", best_len)','滑动窗口把「枚举所有子串 O(n²)」优化成「一次扫描 O(n)」，是字符串题的高频套路。',1,'最长无重复子串','','',30,25,6,'python',1),
('cp-sr-12','SENIOR',3,'链表反转','用列表模拟链表并反转','用「值数组 + next 下标数组」模拟单链表，反转后按新顺序输出节点值。','反转就是让每个节点的 next 指向它的前驱；从头遍历一遍逐个改指针。','values = [1, 2, 3, 4, 5]\nnxt = [1, 2, 3, 4, -1]\n\nprev = -1\ncurrent = 0\nwhile current != -1:\n    # TODO: 反转指针\n    pass\n\norder = []\nnode = prev\nwhile node != -1:\n    order.append(values[node])\n    node = nxt[node]\nprint("反转后：", order)','values = [1, 2, 3, 4, 5]\nnxt = [1, 2, 3, 4, -1]\n\nprev = -1\ncurrent = 0\nwhile current != -1:\n    following = nxt[current]\n    nxt[current] = prev\n    prev = current\n    current = following\n\norder = []\nnode = prev\nwhile node != -1:\n    order.append(values[node])\n    node = nxt[node]\nprint("反转后：", order)','反转链表的三指针写法（prev / current / following）是最经典的指针练习。',1,'反转后','','',30,25,7,'python',1),
('cp-sr-13','SENIOR',3,'循环队列模拟','实现固定容量的循环队列','用固定长度数组实现循环队列（入队/出队/判空/判满），按脚本演示一遍。','用 head 下标 + count 计数配合取模实现环形复用。','class CircularQueue:\n    def __init__(self, size):\n        self.size = size\n        self.buf = [None] * size\n        self.head = 0\n        self.count = 0\n\n    def enqueue(self, value):\n        # TODO: 入队与出队\n        pass\n\n    def dequeue(self):\n        pass\n\nq = CircularQueue(3)','class CircularQueue:\n    def __init__(self, size):\n        self.size = size\n        self.buf = [None] * size\n        self.head = 0\n        self.count = 0\n\n    def enqueue(self, value):\n        if self.count == self.size:\n            print("队列已满，", value, "入队失败")\n            return False\n        index = (self.head + self.count) % self.size\n        self.buf[index] = value\n        self.count += 1\n        print(value, "入队，队列：", self.buf)\n        return True\n\n    def dequeue(self):\n        if self.count == 0:\n            print("队列为空")\n            return None\n        value = self.buf[self.head]\n        self.buf[self.head] = None\n        self.head = (self.head + 1) % self.size\n        self.count -= 1\n        print(value, "出队，队列：", self.buf)\n        return value\n\nq = CircularQueue(3)\nq.enqueue(1)\nq.enqueue(2)\nq.enqueue(3)\nq.enqueue(4)\nq.dequeue()\nq.enqueue(5)\nq.dequeue()\nq.dequeue()\nq.dequeue()','取模实现「环形复用」是队列的核心；用 count 而不是空槽判空满，可以避免浪费一个格子。',1,'入队,出队','','',30,30,8,'python',1),
('cp-sr-14','SENIOR',4,'后缀表达式求值','用栈计算后缀表达式的值','后缀表达式（逆波兰）如 3 4 + 5 * 等于 35，请用栈求值。','遇到数字入栈；遇到运算符弹出两个数计算后把结果压回栈。','tokens = ["3", "4", "+", "5", "*"]\n\ndef eval_rpn(items):\n    stack = []\n    for token in items:\n        # TODO: 数字入栈，运算符弹两数计算再入栈\n        pass\n    return stack[0]\n\nprint("3 4 + 5 *  =", eval_rpn(tokens))','tokens = ["3", "4", "+", "5", "*"]\n\ndef eval_rpn(items):\n    stack = []\n    for token in items:\n        if token in "+-*/":\n            b = stack.pop()\n            a = stack.pop()\n            if token == "+":\n                stack.append(a + b)\n            elif token == "-":\n                stack.append(a - b)\n            elif token == "*":\n                stack.append(a * b)\n            else:\n                stack.append(int(a / b))\n        else:\n            stack.append(int(token))\n    return stack[0]\n\nprint("3 4 + 5 *  =", eval_rpn(tokens))','后缀表达式天然适合栈：不需要括号与优先级规则，这也是编译器的常用处理方式。',1,'35','','',50,30,1,'python',1),
('cp-sr-15','SENIOR',4,'二叉树层序遍历','用数组模拟二叉树并层序输出','用下标模拟完全二叉树（左子 2i+1、右子 2i+2），按层从左到右输出节点值。','用队列保存「本层待访问节点」，出队时把左右孩子入队。','tree = [1, 2, 3, 4, 5, 6, 7]\n\ndef level_order(nodes):\n    if not nodes:\n        return []\n    result = []\n    queue = [0]\n    # TODO: 逐层遍历\n    return result\n\nprint("层序遍历：", level_order(tree))','tree = [1, 2, 3, 4, 5, 6, 7]\n\ndef level_order(nodes):\n    if not nodes:\n        return []\n    result = []\n    queue = [0]\n    while queue:\n        index = queue.pop(0)\n        if index >= len(nodes):\n            continue\n        result.append(nodes[index])\n        queue.append(index * 2 + 1)\n        queue.append(index * 2 + 2)\n    return result\n\nprint("层序遍历：", level_order(tree))','层序遍历 = 队列；前中后序遍历 = 递归（栈）。BFS 与 DFS 的区别就在这里。',1,'层序遍历','','',50,28,2,'python',1),
('cp-sr-16','SENIOR',3,'爬楼梯（动态规划）','求爬到第 n 阶的方法数','每次可以走 1 阶或 2 阶，求走到第 10 阶共有多少种走法。','f(n) = f(n-1) + f(n-2)，用一个数组从小到大递推即可。','def climb(n):\n    # TODO: 动态规划求方法数\n    return 0\n\nfor step in [5, 10]:\n    print("爬到第", step, "阶共有", climb(step), "种走法")','def climb(n):\n    if n <= 2:\n        return n\n    dp = [0] * (n + 1)\n    dp[1] = 1\n    dp[2] = 2\n    for i in range(3, n + 1):\n        dp[i] = dp[i - 1] + dp[i - 2]\n    return dp[n]\n\nfor step in [5, 10]:\n    print("爬到第", step, "阶共有", climb(step), "种走法")','「当前状态由前几个状态推出」就是动态规划；爬楼梯是最容易上手的 DP 入门题。',1,'种走法','','',30,18,3,'python',1),
('cp-sr-17','SENIOR',4,'零钱兑换','用最少的硬币数凑出目标金额','给定硬币面值与目标金额，求最少硬币数（凑不出输出 -1）。','dp[amount] 表示凑出该金额的最少硬币数，逐个金额尝试每种硬币。','coins = [1, 2, 5]\namount = 11\n\ndef coin_change(coins, amount):\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    # TODO: 填表\n    return dp[amount]\n\nresult = coin_change(coins, amount)\nprint("凑出", amount, "元最少需要", result, "枚硬币")','coins = [1, 2, 5]\namount = 11\n\ndef coin_change(coins, amount):\n    dp = [float("inf")] * (amount + 1)\n    dp[0] = 0\n    for value in range(1, amount + 1):\n        for coin in coins:\n            if coin <= value:\n                dp[value] = min(dp[value], dp[value - coin] + 1)\n    return dp[amount] if dp[amount] != float("inf") else -1\n\nresult = coin_change(coins, amount)\nprint("凑出", amount, "元最少需要", result, "枚硬币")','完全背包的入门形态：用 inf 表示凑不出，最后要判无解。',1,'枚硬币','','',50,30,4,'python',1),
('cp-sr-18','SENIOR',4,'最长公共子序列','求两个字符串的最长公共子序列长度','如 abcde 与 ace 的最长公共子序列是 ace，长度为 3。','二维 dp：字符相同则取对角 + 1，否则取上方与左方的较大值。','a = "abcde"\nb = "ace"\n\ndef lcs(s, t):\n    dp = [[0] * (len(t) + 1) for _ in range(len(s) + 1)]\n    # TODO: 填二维表\n    return dp[len(s)][len(t)]\n\nprint("最长公共子序列长度：", lcs(a, b))','a = "abcde"\nb = "ace"\n\ndef lcs(s, t):\n    dp = [[0] * (len(t) + 1) for _ in range(len(s) + 1)]\n    for i in range(1, len(s) + 1):\n        for j in range(1, len(t) + 1):\n            if s[i - 1] == t[j - 1]:\n                dp[i][j] = dp[i - 1][j - 1] + 1\n            else:\n                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])\n    return dp[len(s)][len(t)]\n\nprint("最长公共子序列长度：", lcs(a, b))','二维 DP 的移项关系也是 diff 工具与文本相似度计算的基础。',1,'长度','','',50,30,5,'python',1),
('cp-sr-19','SENIOR',4,'图的 BFS 最短路','求无权图中两点的最短跳数','用邻接表存图，BFS 求从起点到各点的最少跳数。','BFS 按层扩展，第一次到达某点时经过的层数就是最短距离。','graph = {\n    "A": ["B", "C"],\n    "B": ["A", "D", "E"],\n    "C": ["A", "F"],\n    "D": ["B"],\n    "E": ["B", "F"],\n    "F": ["C", "E", "G"],\n    "G": ["F"],\n}\n\ndef bfs(graph, start):\n    distance = {start: 0}\n    queue = [start]\n    # TODO: 层序扩展并记录距离\n    return distance\n\ndist = bfs(graph, "A")\nprint("A 到 G 的最短跳数：", dist.get("G"))','graph = {\n    "A": ["B", "C"],\n    "B": ["A", "D", "E"],\n    "C": ["A", "F"],\n    "D": ["B"],\n    "E": ["B", "F"],\n    "F": ["C", "E", "G"],\n    "G": ["F"],\n}\n\ndef bfs(graph, start):\n    distance = {start: 0}\n    queue = [start]\n    while queue:\n        node = queue.pop(0)\n        for nxt in graph[node]:\n            if nxt not in distance:\n                distance[nxt] = distance[node] + 1\n                queue.append(nxt)\n    return distance\n\ndist = bfs(graph, "A")\nprint("A 到 G 的最短跳数：", dist.get("G"))','无权图最短路用 BFS；带权图要换 Dijkstra。这是导航与社交推荐的基础。',1,'最短跳数','','',50,30,6,'python',1),
('cp-sr-20','SENIOR',4,'图的连通分量','统计无向图有几个连通分量','给出 n 个点与若干条边，求连通分量个数与每个分量包含的点。','从每个未访问点出发做一次 DFS/BFS 扩散，就得到一个连通分量。','n = 7\nedges = [(0, 1), (1, 2), (3, 4), (5, 6)]\n\ndef components(n, edges):\n    graph = {i: [] for i in range(n)}\n    for a, b in edges:\n        graph[a].append(b)\n        graph[b].append(a)\n    visited = set()\n    result = []\n    # TODO: DFS 找连通分量\n    return result\n\nparts = components(n, edges)\nprint("连通分量个数：", len(parts))\nfor part in parts:\n    print("  分量：", sorted(part))','n = 7\nedges = [(0, 1), (1, 2), (3, 4), (5, 6)]\n\ndef components(n, edges):\n    graph = {i: [] for i in range(n)}\n    for a, b in edges:\n        graph[a].append(b)\n        graph[b].append(a)\n    visited = set()\n    result = []\n    for start in range(n):\n        if start in visited:\n            continue\n        stack = [start]\n        part = set()\n        while stack:\n            node = stack.pop()\n            if node in part:\n                continue\n            part.add(node)\n            visited.add(node)\n            stack.extend(graph[node])\n        result.append(part)\n    return result\n\nparts = components(n, edges)\nprint("连通分量个数：", len(parts))\nfor part in parts:\n    print("  分量：", sorted(part))','「一次扩散 = 一个分量」是朋友圈、岛屿数量、网络聚类的统一解法。',1,'连通分量','','',50,30,7,'python',1),
('cp-sr-21','SENIOR',4,'并查集：朋友圈','用并查集统计朋友圈数量','给定好友关系，用并查集合并集合，最后统计有几个朋友圈。','find 找根并做路径压缩；union 把两个根接起来。','n = 6\nrelations = [(0, 1), (1, 2), (3, 4)]\n\nparent = list(range(n))\n\ndef find(x):\n    # TODO: 路径压缩\n    return x\n\ndef union(a, b):\n    # TODO: 合并\n    pass\n\nfor a, b in relations:\n    union(a, b)\n\ncircles = len({find(i) for i in range(n)})\nprint("朋友圈数量：", circles)','n = 6\nrelations = [(0, 1), (1, 2), (3, 4)]\n\nparent = list(range(n))\n\ndef find(x):\n    while parent[x] != x:\n        parent[x] = parent[parent[x]]\n        x = parent[x]\n    return x\n\ndef union(a, b):\n    root_a, root_b = find(a), find(b)\n    if root_a != root_b:\n        parent[root_b] = root_a\n\nfor a, b in relations:\n    union(a, b)\n\ncircles = len({find(i) for i in range(n)})\nprint("朋友圈数量：", circles)','并查集擅长「动态合并 + 查询是否同组」，路径压缩后接近 O(1)。',1,'朋友圈数量','','',50,28,8,'python',1),
('cp-sr-22','SENIOR',4,'下一个更大元素','用单调栈求右侧第一个更大的数','对数组中每个元素，找出它右边第一个比它大的元素，没有则输出 -1。','维护一个「从栈底到栈顶递减」的栈：新元素比栈顶大时，就为栈顶元素找到了答案。','data = [2, 1, 2, 4, 3]\n\ndef next_greater(nums):\n    result = [-1] * len(nums)\n    stack = []\n    # TODO: 单调栈\n    return result\n\nprint("下一个更大元素：", next_greater(data))','data = [2, 1, 2, 4, 3]\n\ndef next_greater(nums):\n    result = [-1] * len(nums)\n    stack = []\n    for i, value in enumerate(nums):\n        while stack and nums[stack[-1]] < value:\n            result[stack.pop()] = value\n        stack.append(i)\n    return result\n\nprint("下一个更大元素：", next_greater(data))','单调栈把「找右边第一个更大」从 O(n²) 降到 O(n)，是柱状图最大矩形等题的前置技巧。',1,'下一个更大元素','','',50,28,9,'python',1),
('cp-sr-23','SENIOR',3,'学生管理类','用面向对象封装学生信息与成绩','定义 Student 类（姓名、成绩列表、平均分方法、等级方法），创建 3 个学生并按平均分排序输出。','__init__ 初始化，方法封装行为；排序用 key=lambda s: s.average()。','class Student:\n    def __init__(self, name, scores):\n        self.name = name\n        self.scores = scores\n\n    def average(self):\n        # TODO: 返回平均分\n        return 0\n\n    def level(self):\n        # TODO: 按平均分返回等级\n        return "待提高"\n\nstudents = [Student("小明", [88, 92, 79]), Student("小红", [95, 98, 91]), Student("小刚", [60, 72, 65])]','class Student:\n    def __init__(self, name, scores):\n        self.name = name\n        self.scores = scores\n\n    def average(self):\n        return round(sum(self.scores) / len(self.scores), 1)\n\n    def level(self):\n        avg = self.average()\n        if avg >= 90:\n            return "优秀"\n        if avg >= 75:\n            return "良好"\n        if avg >= 60:\n            return "及格"\n        return "待提高"\n\nstudents = [Student("小明", [88, 92, 79]), Student("小红", [95, 98, 91]), Student("小刚", [60, 72, 65])]\nfor student in sorted(students, key=lambda s: -s.average()):\n    print(f"{student.name} 平均分 {student.average()} 等级 {student.level()}")','把「数据 + 行为」封装在一起就是面向对象；把方法作为排序 key 是函数式与面向对象的结合。',1,'平均分,等级','','',30,25,10,'python',1),
('cp-sr-24','SENIOR',4,'简易计算器','解析并计算带括号的四则运算式','实现一个支持 + - * / 与括号、优先级的计算器，对给定表达式求值。','把中缀表达式转成后缀（调度场算法）再求值。','expression = "3 + 4 * (2 - 1)"\n\ndef calculate(expr):\n    # TODO: 解析并计算表达式\n    return 0\n\nprint(expression, "=", calculate(expression))','expression = "3 + 4 * (2 - 1)"\n\ndef calculate(expr):\n    tokens = expr.replace("(", " ( ").replace(")", " ) ").split()\n    prec = {"+": 1, "-": 1, "*": 2, "/": 2}\n\n    def to_rpn(items):\n        output, ops = [], []\n        for token in items:\n            if token in prec:\n                while ops and ops[-1] != "(" and prec[ops[-1]] >= prec[token]:\n                    output.append(ops.pop())\n                ops.append(token)\n            elif token == "(":\n                ops.append(token)\n            elif token == ")":\n                while ops and ops[-1] != "(":\n                    output.append(ops.pop())\n                ops.pop()\n            else:\n                output.append(token)\n        while ops:\n            output.append(ops.pop())\n        return output\n\n    stack = []\n    for token in to_rpn(tokens):\n        if token in prec:\n            b = stack.pop()\n            a = stack.pop()\n            if token == "+":\n                stack.append(a + b)\n            elif token == "-":\n                stack.append(a - b)\n            elif token == "*":\n                stack.append(a * b)\n            else:\n                stack.append(a / b)\n        else:\n            stack.append(float(token))\n    value = stack[0]\n    return int(value) if value == int(value) else round(value, 4)\n\nprint(expression, "=", calculate(expression))','调度场算法（中缀 → 后缀 → 求值）是编译原理最经典的入门例子，也是本题库的高阶综合题。',1,'= 7','','',50,35,11,'python',1)
ON DUPLICATE KEY UPDATE `stage`=VALUES(`stage`), `difficulty`=VALUES(`difficulty`), `title`=VALUES(`title`), `goal`=VALUES(`goal`), `description`=VALUES(`description`), `hint`=VALUES(`hint`), `starter_code`=VALUES(`starter_code`), `reference_code`=VALUES(`reference_code`), `solution_notes`=VALUES(`solution_notes`), `judge_type`=VALUES(`judge_type`), `expected_keywords`=VALUES(`expected_keywords`), `score`=VALUES(`score`), `estimate_minutes`=VALUES(`estimate_minutes`), `sort`=VALUES(`sort`), `status`=VALUES(`status`);

-- =============================================================
-- 演示比赛（3 场，可随时在管理端删除）：
--   小学高年级：今天 00:00 ~ 7 天后 23:59（进行中）
--   初中：今天 00:00 ~ 7 天后 23:59（进行中）
--   高中：明天 09:00 ~ 9 天后 21:00（未开始）
-- =============================================================
INSERT INTO `coding_contest` (`contest_id`,`title`,`stage`,`description`,`start_time`,`end_time`,`duration_minutes`,`allow_answer`,`status`,`create_by`) VALUES
('cc-ph-demo','三年级信息科技挑战赛','PRIMARY_HIGH','## 比赛说明\n\n- 共 8 道题，由易到难，满分 220 分；\n- 比赛期间**不能查看答案**，请先自己思考，可让 AI 陪学给思路；\n- 提交后可以看到每题结果与讲解。','2026-10-06 00:00:00','2026-10-13 23:59:59',NULL,0,1,1),
('cc-jr-demo','初中编程挑战赛','JUNIOR','## 比赛说明\n\n- 共 12 道题，覆盖列表、字符串、双指针、递归；\n- 比赛期间不能查看答案；\n- 鼓励先写伪代码再动手。','2026-10-06 00:00:00','2026-10-13 23:59:59',120,0,1,1),
('cc-sr-demo','高中算法进阶赛','SENIOR','## 比赛说明\n\n- 共 12 道题，含排序、动态规划、图论；\n- 限时 120 分钟，进入比赛后开始计时；\n- 比赛期间不能查看答案。','2026-10-07 09:00:00','2026-10-15 21:00:00',120,0,1,1)
ON DUPLICATE KEY UPDATE `title`=VALUES(`title`), `stage`=VALUES(`stage`), `description`=VALUES(`description`), `start_time`=VALUES(`start_time`), `end_time`=VALUES(`end_time`), `duration_minutes`=VALUES(`duration_minutes`), `allow_answer`=VALUES(`allow_answer`), `status`=VALUES(`status`);

-- 演示比赛赛题（小高 8 题 / 初中 12 题 / 高中前 12 题）
INSERT INTO `coding_contest_problem` (`contest_id`,`problem_id`,`sort`,`score_override`) VALUES
('cc-ph-demo','cp-ph-01',1,NULL),('cc-ph-demo','cp-ph-02',2,NULL),('cc-ph-demo','cp-ph-03',3,NULL),('cc-ph-demo','cp-ph-04',4,NULL),
('cc-ph-demo','cp-ph-05',5,NULL),('cc-ph-demo','cp-ph-06',6,NULL),('cc-ph-demo','cp-ph-07',7,NULL),('cc-ph-demo','cp-ph-08',8,NULL),
('cc-jr-demo','cp-jr-01',1,NULL),('cc-jr-demo','cp-jr-02',2,NULL),('cc-jr-demo','cp-jr-03',3,NULL),('cc-jr-demo','cp-jr-04',4,NULL),
('cc-jr-demo','cp-jr-05',5,NULL),('cc-jr-demo','cp-jr-06',6,NULL),('cc-jr-demo','cp-jr-07',7,NULL),('cc-jr-demo','cp-jr-08',8,NULL),
('cc-jr-demo','cp-jr-09',9,NULL),('cc-jr-demo','cp-jr-10',10,NULL),('cc-jr-demo','cp-jr-11',11,NULL),('cc-jr-demo','cp-jr-12',12,NULL),
('cc-sr-demo','cp-sr-01',1,NULL),('cc-sr-demo','cp-sr-02',2,NULL),('cc-sr-demo','cp-sr-03',3,NULL),('cc-sr-demo','cp-sr-04',4,NULL),
('cc-sr-demo','cp-sr-05',5,NULL),('cc-sr-demo','cp-sr-06',6,NULL),('cc-sr-demo','cp-sr-07',7,NULL),('cc-sr-demo','cp-sr-08',8,NULL),
('cc-sr-demo','cp-sr-09',9,NULL),('cc-sr-demo','cp-sr-10',10,NULL),('cc-sr-demo','cp-sr-11',11,NULL),('cc-sr-demo','cp-sr-12',12,NULL)
ON DUPLICATE KEY UPDATE `sort`=VALUES(`sort`), `score_override`=VALUES(`score_override`);
