server:
  port: 8084
  main:
    web-application-type: reactive
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/easymall?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  ai:
    # MCP 服务
    mcp:
      server:
        protocol: STREAMABLE # STREAMABLE STATELESS
        name: easymall-mcp  # 服务器名称
        version: 1.0.0
        streamable-http:
          mcp-endpoint: /mcp  #默认是mcp
          keep-alive-interval: 60s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#项目目录
project:
  folder: c:/webser/web_app/easymall/
#支付宝
alipay:
  appid: 9021000158635250   # 沙箱 9021000158635250
  # 应用私钥
  # 沙箱 MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCEIjMVcWf8bvYRlj4miZgklAPYfmmayGGi15aB0vDzqreIzmU2nysnz2qOcWS5m8oIJ4ynBCau6Hi+0HVE53n0+TsZ8LDesnTkKTPmsSwnNUqlZ9Avgql8mIIcl8tQN2ljc4Vi5GBibAy/bRqzugLGIloc1xgMMUFQgX/+To8qgJ73H8ryk8ieOpVYcTJlq5Ri8UF7JEzmU/gKfneFR+lnizzirvPiG7VoPXRd/pR5b1mgl1C9rm2wSQ+YuA8L5OytWQ4VxMpnH9nXAwVaJENNSxStHQiFUgELbiqHU1CZA9NM8dkhal/ch4DMk57SDfXAnuox4a4i9nkN0xQSLn7XAgMBAAECggEAEe4GGonJ/4IbF+XYRyhyobwIDY+RyvQX853niXRTR+1JfGHtcA0HMR6/KdcPQPR35MVhG6S/jwpyoAnvb8stTGWpdGqpxX5XyEIjDdHK2QMtPuaoZFoJn6OePD0I1LjAL0OUvQeaYKCi1jL65Zp/F92/dpxlYfopD8CS2rJUUQLy9TV3CxoM5iEQ2rhKHxVkugVo64Kq1NIkWZvsk8Zn7kTTG0gLfdAoZmqjlryAiU0QUjOpxcPuzoAdnV7XgMMqxSBxKl5RLZbOUtv2/z9yupsLToHKdsuYch5RcrMLJpRintXGDKvy9CpngRW2IjBLgySe8sU/S94NRnmogYvxuQKBgQDIj1ZXCClE+p1K5mXRv4LXYOfdYiAVfxAbOaz5+SVD6FR/7I8fcSvYvSjWgtP2c3qytLvU7CVptndqGpeBko5QfkVOhivbFZGnonOg5UtKoiCgur/PEntrKcduMOZFgpcVl5PiY+aFdvVnXIAzDcJhXJyXofIlvhm+ZGm1HcIKrQKBgQCoqKjyA4tNXvzrr5YTjC3ArkN0mEP4FmARj2DXvqgNbR0xi2ECaubf2NmpTWsQFO+uzR0W2euuCP3jZhsdl24OUIzJswUZdwlC/2H//Bp2NK+1gcbQlzGwOsC+F9Rc8GHTPAxxeVHGal4mHl9/dbH7hU+6LtyAu8JbP10Fn7EEEwKBgHvdIoqvrKVATkKC1qFasJkJ7Ukpn/0Gs1DNJwpfF+e/peg3lhDqGRVLhdwtgnDz0vRpcJPIoDaQjWGHOMi6VZBa27zqWk19Ha61Qso8smpOhO4fR/TASl7dt6BTLPQC+gJI0fmAj08gL+F9HGPrfIAa7U8solsy871FUI+d6EglAoGADMRfrZpJFD1JhgnPoYEuAXTvlEbmdkQzV4D0AsDi9ck5uYNkf4taGL3QlDlRDnGXRzMtrYonhhAWL/2Nteq9oQXF8orDqw7Qu6qbX4ZU9ne8iU/enfGkCEQaTQl+wN5NeXEFPB3D6/InWFlaP0rIg1KvG1fqxy/vYXrlbsSM4NMCgYEAlsLf1djKWz4g5XPc6tnowsPFQcZZt5Epg+sa0I/KqYELE9pwViAm6R03Tn7hZm12n6bdZXZLre+goNCZd6T2xVETsd2TUDhKURPId0CdQTurmSRv4EaYleu9zccJqvYD5gFxYQDz1BT8+Xx9Wkf3tfYg/VBPlLOkb0oHHxxtJOg=
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCEIjMVcWf8bvYRlj4miZgklAPYfmmayGGi15aB0vDzqreIzmU2nysnz2qOcWS5m8oIJ4ynBCau6Hi+0HVE53n0+TsZ8LDesnTkKTPmsSwnNUqlZ9Avgql8mIIcl8tQN2ljc4Vi5GBibAy/bRqzugLGIloc1xgMMUFQgX/+To8qgJ73H8ryk8ieOpVYcTJlq5Ri8UF7JEzmU/gKfneFR+lnizzirvPiG7VoPXRd/pR5b1mgl1C9rm2wSQ+YuA8L5OytWQ4VxMpnH9nXAwVaJENNSxStHQiFUgELbiqHU1CZA9NM8dkhal/ch4DMk57SDfXAnuox4a4i9nkN0xQSLn7XAgMBAAECggEAEe4GGonJ/4IbF+XYRyhyobwIDY+RyvQX853niXRTR+1JfGHtcA0HMR6/KdcPQPR35MVhG6S/jwpyoAnvb8stTGWpdGqpxX5XyEIjDdHK2QMtPuaoZFoJn6OePD0I1LjAL0OUvQeaYKCi1jL65Zp/F92/dpxlYfopD8CS2rJUUQLy9TV3CxoM5iEQ2rhKHxVkugVo64Kq1NIkWZvsk8Zn7kTTG0gLfdAoZmqjlryAiU0QUjOpxcPuzoAdnV7XgMMqxSBxKl5RLZbOUtv2/z9yupsLToHKdsuYch5RcrMLJpRintXGDKvy9CpngRW2IjBLgySe8sU/S94NRnmogYvxuQKBgQDIj1ZXCClE+p1K5mXRv4LXYOfdYiAVfxAbOaz5+SVD6FR/7I8fcSvYvSjWgtP2c3qytLvU7CVptndqGpeBko5QfkVOhivbFZGnonOg5UtKoiCgur/PEntrKcduMOZFgpcVl5PiY+aFdvVnXIAzDcJhXJyXofIlvhm+ZGm1HcIKrQKBgQCoqKjyA4tNXvzrr5YTjC3ArkN0mEP4FmARj2DXvqgNbR0xi2ECaubf2NmpTWsQFO+uzR0W2euuCP3jZhsdl24OUIzJswUZdwlC/2H//Bp2NK+1gcbQlzGwOsC+F9Rc8GHTPAxxeVHGal4mHl9/dbH7hU+6LtyAu8JbP10Fn7EEEwKBgHvdIoqvrKVATkKC1qFasJkJ7Ukpn/0Gs1DNJwpfF+e/peg3lhDqGRVLhdwtgnDz0vRpcJPIoDaQjWGHOMi6VZBa27zqWk19Ha61Qso8smpOhO4fR/TASl7dt6BTLPQC+gJI0fmAj08gL+F9HGPrfIAa7U8solsy871FUI+d6EglAoGADMRfrZpJFD1JhgnPoYEuAXTvlEbmdkQzV4D0AsDi9ck5uYNkf4taGL3QlDlRDnGXRzMtrYonhhAWL/2Nteq9oQXF8orDqw7Qu6qbX4ZU9ne8iU/enfGkCEQaTQl+wN5NeXEFPB3D6/InWFlaP0rIg1KvG1fqxy/vYXrlbsSM4NMCgYEAlsLf1djKWz4g5XPc6tnowsPFQcZZt5Epg+sa0I/KqYELE9pwViAm6R03Tn7hZm12n6bdZXZLre+goNCZd6T2xVETsd2TUDhKURPId0CdQTurmSRv4EaYleu9zccJqvYD5gFxYQDz1BT8+Xx9Wkf3tfYg/VBPlLOkb0oHHxxtJOg=
  appCertPath: alipay-sandbox/appPublicCert.crt
  alipayPublicCertPath: alipay-sandbox/alipayPublicCert.crt
  alipayRootCertPath: alipay-sandbox/alipayRootCert.crt
  #沙箱 https://openapi-sandbox.dl.alipaydev.com/gateway.do  正式 https://openapi.alipay.com/gateway.do
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do